import * as MessageHandlers from '../logic/message-handler';
import {ErrorMessageFunction} from '../../../shared/types';

export const DEFAULT_MESSAGE_HANDLER_MAP = new Map<string, ErrorMessageFunction>([
  ['min', MessageHandlers.min],
  ['max', MessageHandlers.max],
  ['required', MessageHandlers.required],
  ['email', MessageHandlers.email],
  ['minlength', MessageHandlers.minLength],
  ['maxlength', MessageHandlers.maxLength],
  ['pattern', MessageHandlers.pattern],
  ['isTruthy', MessageHandlers.isTruthy],
  ['isFalsy', MessageHandlers.isFalsy],
  ['lessThan', MessageHandlers.lessThan],
  ['greaterThan', MessageHandlers.greaterThan],
  ['equalTo', MessageHandlers.equalTo],
  ['lessOrEqual', MessageHandlers.lessOrEqual],
  ['greaterOrEqual', MessageHandlers.greaterOrEqual],
  ['isDate', MessageHandlers.isDate],
  ['dateBefore', MessageHandlers.dateBefore],
  ['dateAfter', MessageHandlers.dateAfter],
  ['dateOn', MessageHandlers.dateOn],
  ['dateOnOrBefore', MessageHandlers.dateOnOrBefore],
  ['dateOnOrAfter', MessageHandlers.dateOnOrAfter],
  ['ageLess', MessageHandlers.ageLess],
  ['ageGreater', MessageHandlers.ageGreater],
  ['ageEqual', MessageHandlers.ageEqual],
  ['ageLessOrEqual', MessageHandlers.ageLessOrEqual],
  ['ageGreaterOrEqual', MessageHandlers.ageGreaterOrEqual],
  ['mask', MessageHandlers.mask],
]);
